import { Download, LogOut, RotateCcw, Save, ShieldCheck, UserRound } from 'lucide-react'
import type { PlayerProfile, Settings } from '../types'
import { exportProfile } from '../store/profile'

interface Props { profile: PlayerProfile; onChange: (profile: PlayerProfile) => void; onLogout: () => void; onEventReset: () => void; notify: (text: string, tone?: 'success' | 'warning') => void }

export default function ProfileScreen({ profile, onChange, onLogout, onEventReset, notify }: Props) {
  const accuracy = profile.stats.classificationTotal ? Math.round(profile.stats.classificationCorrect / profile.stats.classificationTotal * 100) : 0
  const setting = <K extends keyof Settings>(key: K, value: Settings[K]) => onChange({ ...profile, settings: { ...profile.settings, [key]: value } })
  return <div className="profile-screen screen-enter"><header className="profile-hero pixel-panel"><div className="avatar-block"><UserRound /></div><div><span className="eyebrow">LOCAL ACTION PROFILE</span><h1>{profile.username}</h1><p>LV.{profile.level} · 存档仅在本机保存 · 创建于 {new Date(profile.createdAt).toLocaleDateString('zh-CN')}</p></div><div className="xp-block"><span><i style={{ width: `${profile.xp / (profile.level * 100) * 100}%` }} /></span><small>{profile.xp} / {profile.level * 100} XP</small></div></header>
    <section className="stats-board"><article><b>{profile.stats.runs}</b><span>行动次数</span></article><article><b>{profile.stats.victories}</b><span>稳定原型行动</span></article><article><b>{profile.stats.enemiesPurified}</b><span>净化污染体</span></article><article><b>{accuracy}%</b><span>分类准确率</span></article><article><b>{profile.stats.valuePreserved}</b><span>价值保留</span></article><article><b>{profile.storiesCompleted.length}</b><span>完成故事</span></article></section>
    <div className="profile-grid"><section className="settings-panel pixel-panel"><span className="eyebrow">GAME SETTINGS</span><h2>游戏设置</h2><label><span><b>总音量</b><small>界面、战斗与环境音统一比例</small></span><input type="range" min="0" max="1" step=".05" value={profile.settings.masterVolume} onChange={(event) => setting('masterVolume', Number(event.target.value))} /></label><label><span><b>屏幕震动</b><small>受击、Boss破壳时的镜头反馈</small></span><input type="checkbox" checked={profile.settings.screenShake} onChange={(event) => setting('screenShake', event.target.checked)} /></label><label><span><b>减少动态</b><small>降低转场、呼吸与粒子动画</small></span><input type="checkbox" checked={profile.settings.reducedMotion} onChange={(event) => setting('reducedMotion', event.target.checked)} /></label><label><span><b>高对比度</b><small>增强文字与交互边界</small></span><input type="checkbox" checked={profile.settings.highContrast} onChange={(event) => setting('highContrast', event.target.checked)} /></label><label><span><b>展会模式</b><small>突出快速开始，便于现场公共设备使用</small></span><input type="checkbox" checked={profile.settings.eventMode} onChange={(event) => setting('eventMode', event.target.checked)} /></label></section>
      <section className="save-panel pixel-panel"><span className="eyebrow">SAVE & PRIVACY</span><h2>本机存档</h2><div className="privacy-note"><ShieldCheck /><p>不上传账号、选择或统计数据。用户名只是本机存档标签，不设置密码，也不适合写入真实敏感信息。</p></div><button className="secondary-button" onClick={() => { exportProfile(profile); notify('存档文件已导出', 'success') }}><Download /> 导出存档备份</button><button className="secondary-button" onClick={() => notify('存档会在每次选择后自动保存', 'success')}><Save /> 检查自动保存</button>{profile.settings.eventMode && <button className="danger-button" onClick={onEventReset}><RotateCcw /> 清空当前展会存档</button>}<button className="secondary-button" onClick={onLogout}><LogOut /> 返回用户名选择</button></section></div>
  </div>
}
