import { Download, LogOut, RotateCcw, Save, Upload } from 'lucide-react'
import { useRef } from 'react'
import GameIcon from '../components/GameIcon'
import type { PlayerProfile, Settings } from '../types'
import type { GameIconName } from '../components/GameIcon'
import { exportProfile, importProfile } from '../store/profile'

interface Props { profile: PlayerProfile; onChange: (profile: PlayerProfile) => void; onLogout: () => void; onEventReset: () => void; notify: (text: string, tone?: 'success' | 'warning') => void }

export default function ProfileScreen({ profile, onChange, onLogout, onEventReset, notify }: Props) {
  const importRef = useRef<HTMLInputElement>(null)
  const accuracy = profile.stats.classificationTotal ? Math.round(profile.stats.classificationCorrect / profile.stats.classificationTotal * 100) : 0
  const stats: { value: string | number; label: string; note: string; icon: GameIconName; tone: string }[] = [
    { value: profile.stats.runs, label: '行动出发', note: '进入城市节点', icon: 'map', tone: 'cyan' },
    { value: profile.stats.victories, label: '行动完成', note: '成功稳定原型', icon: 'prototype', tone: 'orange' },
    { value: profile.stats.enemiesPurified, label: '污染体净化', note: '击破污染外壳', icon: 'pollution', tone: 'violet' },
    { value: `${accuracy}%`, label: '分类准确率', note: '材料判断记录', icon: 'knowledge', tone: 'lime' },
    { value: profile.stats.valuePreserved, label: '价值保留', note: '累计行动积分', icon: 'value', tone: 'blue' },
    { value: profile.storiesCompleted.length, label: '故事完成', note: '已读物品记忆', icon: 'theater', tone: 'yellow' },
  ]
  const setting = <K extends keyof Settings>(key: K, value: Settings[K]) => onChange({ ...profile, settings: { ...profile.settings, [key]: value } })
  return <div className="profile-screen screen-enter"><header className="profile-hero pixel-panel"><div className="avatar-block"><GameIcon name="profile" size={92} /></div><div><span className="eyebrow">LOCAL ACTION PROFILE</span><h1>{profile.username}</h1><p>LV.{profile.level} · 存档仅在本机保存 · 创建于 {new Date(profile.createdAt).toLocaleDateString('zh-CN')}</p></div><div className="xp-block"><span><i style={{ width: `${profile.xp / (profile.level * 100) * 100}%` }} /></span><small>{profile.xp} / {profile.level * 100} XP</small></div></header>
    <section className="stats-board" aria-label="行动统计">{stats.map((stat) => <article key={stat.label} className={`profile-stat tone-${stat.tone}`}><GameIcon name={stat.icon} size={44} /><span className="stat-copy"><small>{stat.note}</small><b>{stat.value}</b><strong>{stat.label}</strong></span></article>)}</section>
    <div className="profile-grid"><section className="settings-panel pixel-panel"><span className="eyebrow">GAME SETTINGS</span><h2>游戏设置</h2><label><span><b>总音量</b><small>界面、战斗与程序化配乐统一比例</small></span><input type="range" min="0" max="1" step=".05" value={profile.settings.masterVolume} onChange={(event) => setting('masterVolume', Number(event.target.value))} /></label><label><span><b>音乐音量</b><small>11首分场景原创程序化主题</small></span><input type="range" min="0" max="1" step=".05" value={profile.settings.musicVolume} onChange={(event) => setting('musicVolume', Number(event.target.value))} /></label><label><span><b>剧情语音预览</b><small>使用本机浏览器中文语音；正式配音可按脚本替换</small></span><input type="checkbox" checked={profile.settings.voicePreview} onChange={(event) => setting('voicePreview', event.target.checked)} /></label><label><span><b>语音音量</b><small>仅影响浏览器剧情语音预览</small></span><input type="range" min="0" max="1" step=".05" value={profile.settings.voiceVolume} onChange={(event) => setting('voiceVolume', Number(event.target.value))} /></label><label><span><b>屏幕震动</b><small>受击、Boss破壳时的镜头反馈</small></span><input type="checkbox" checked={profile.settings.screenShake} onChange={(event) => setting('screenShake', event.target.checked)} /></label><label><span><b>减少动态</b><small>降低转场、呼吸与粒子动画</small></span><input type="checkbox" checked={profile.settings.reducedMotion} onChange={(event) => setting('reducedMotion', event.target.checked)} /></label><label><span><b>高对比度</b><small>增强文字与交互边界</small></span><input type="checkbox" checked={profile.settings.highContrast} onChange={(event) => setting('highContrast', event.target.checked)} /></label><label><span><b>展会模式</b><small>5分钟无操作自动重置，结束前30秒提示</small></span><input type="checkbox" checked={profile.settings.eventMode} onChange={(event) => setting('eventMode', event.target.checked)} /></label></section>
      <section className="save-panel pixel-panel"><span className="eyebrow">SAVE & PRIVACY</span><h2>本机存档</h2><div className="privacy-note"><GameIcon name="shield" size={54} /><p>不上传账号、选择或统计数据。用户名只是本机存档标签，不设置密码，也不适合写入真实敏感信息。</p></div><button className="secondary-button" onClick={() => { exportProfile(profile); notify('存档文件已导出', 'success') }}><Download /> 导出存档备份</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { onChange(await importProfile(file)); notify('存档已导入并切换', 'success') } catch (error) { notify(error instanceof Error ? error.message : '导入失败', 'warning') } finally { event.target.value = '' } }} /><button className="secondary-button" onClick={() => importRef.current?.click()}><Upload /> 导入存档备份</button><button className="secondary-button" onClick={() => notify('存档会在每次选择后自动保存', 'success')}><Save /> 检查自动保存</button>{profile.settings.eventMode && <button className="danger-button" onClick={onEventReset}><RotateCcw /> 清空当前展会存档</button>}<button className="secondary-button" onClick={onLogout}><LogOut /> 返回用户名选择</button></section></div>
  </div>
}
